version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "./distributions/sidecar"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "./distributions/tracing"
    schedule:
      interval: "daily"
