project_name: otelcol-distributions
builds:
- id: sidecar
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - "386"
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: "386"
  - goos: windows
    goarch: arm64
  dir: distributions/sidecar/_build
  binary: sidecar
  ldflags:
  - -s
  - -w
  flags:
  - -trimpath
  env:
  - CGO_ENABLED=0
- id: tracing
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - "386"
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: "386"
  - goos: windows
    goarch: arm64
  dir: distributions/tracing/_build
  binary: tracing
  ldflags:
  - -s
  - -w
  flags:
  - -trimpath
  env:
  - CGO_ENABLED=0
archives:
- id: sidecar
  builds:
  - sidecar
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
- id: tracing
  builds:
  - tracing
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
- package_name: sidecar
  contents:
  - src: distributions/sidecar/sidecar.service
    dst: /lib/systemd/system/sidecar.service
  - src: distributions/sidecar/sidecar.conf
    dst: /etc/sidecar/sidecar.conf
    type: config|noreplace
  - src: configs/sidecar.yaml
    dst: /etc/sidecar/config.yaml
    type: config
  scripts:
    preinstall: distributions/sidecar/preinstall.sh
    postinstall: distributions/sidecar/postinstall.sh
    preremove: distributions/sidecar/preremove.sh
  id: sidecar
  builds:
  - sidecar
  formats:
  - apk
  - deb
  - rpm
  maintainer: Juraci Paixão Kröhling <distributions@kroehling.de>
  description: sidecar distribution of the OpenTelemetry Collector
  license: Apache 2.0
- package_name: tracing
  contents:
  - src: distributions/tracing/tracing.service
    dst: /lib/systemd/system/tracing.service
  - src: distributions/tracing/tracing.conf
    dst: /etc/tracing/tracing.conf
    type: config|noreplace
  - src: configs/tracing.yaml
    dst: /etc/tracing/config.yaml
    type: config
  scripts:
    preinstall: distributions/tracing/preinstall.sh
    postinstall: distributions/tracing/postinstall.sh
    preremove: distributions/tracing/preremove.sh
  id: tracing
  builds:
  - tracing
  formats:
  - apk
  - deb
  - rpm
  maintainer: Juraci Paixão Kröhling <distributions@kroehling.de>
  description: tracing distribution of the OpenTelemetry Collector
  license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
dockers:
- goos: linux
  goarch: "386"
  dockerfile: distributions/sidecar/Dockerfile
  image_templates:
  - ghcr.io/jpkrohling/otelcol-distributions/sidecar:{{ .Version }}-386
  extra_files:
  - configs/sidecar.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/386
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
- goos: linux
  goarch: amd64
  dockerfile: distributions/sidecar/Dockerfile
  image_templates:
  - ghcr.io/jpkrohling/otelcol-distributions/sidecar:{{ .Version }}-amd64
  extra_files:
  - configs/sidecar.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/amd64
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
- goos: linux
  goarch: arm64
  dockerfile: distributions/sidecar/Dockerfile
  image_templates:
  - ghcr.io/jpkrohling/otelcol-distributions/sidecar:{{ .Version }}-arm64
  extra_files:
  - configs/sidecar.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/arm64
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
- goos: linux
  goarch: ppc64le
  dockerfile: distributions/sidecar/Dockerfile
  image_templates:
  - ghcr.io/jpkrohling/otelcol-distributions/sidecar:{{ .Version }}-ppc64le
  extra_files:
  - configs/sidecar.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/ppc64le
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
- goos: linux
  goarch: "386"
  dockerfile: distributions/tracing/Dockerfile
  image_templates:
  - ghcr.io/jpkrohling/otelcol-distributions/tracing:{{ .Version }}-386
  extra_files:
  - configs/tracing.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/386
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
- goos: linux
  goarch: amd64
  dockerfile: distributions/tracing/Dockerfile
  image_templates:
  - ghcr.io/jpkrohling/otelcol-distributions/tracing:{{ .Version }}-amd64
  extra_files:
  - configs/tracing.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/amd64
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
- goos: linux
  goarch: arm64
  dockerfile: distributions/tracing/Dockerfile
  image_templates:
  - ghcr.io/jpkrohling/otelcol-distributions/tracing:{{ .Version }}-arm64
  extra_files:
  - configs/tracing.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/arm64
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
- goos: linux
  goarch: ppc64le
  dockerfile: distributions/tracing/Dockerfile
  image_templates:
  - ghcr.io/jpkrohling/otelcol-distributions/tracing:{{ .Version }}-ppc64le
  extra_files:
  - configs/tracing.yaml
  build_flag_templates:
  - --pull
  - --platform=linux/ppc64le
  - --label=org.opencontainers.image.created={{.Date}}
  - --label=org.opencontainers.image.name={{.ProjectName}}
  - --label=org.opencontainers.image.revision={{.FullCommit}}
  - --label=org.opencontainers.image.version={{.Version}}
  - --label=org.opencontainers.image.source={{.GitURL}}
  use: buildx
docker_manifests:
- name_template: ghcr.io/jpkrohling/otelcol-distributions/sidecar:{{ .Version }}
  image_templates:
  - ghcr.io/jpkrohling/otelcol-distributions/sidecar:{{ .Version }}-386
  - ghcr.io/jpkrohling/otelcol-distributions/sidecar:{{ .Version }}-amd64
  - ghcr.io/jpkrohling/otelcol-distributions/sidecar:{{ .Version }}-arm64
  - ghcr.io/jpkrohling/otelcol-distributions/sidecar:{{ .Version }}-ppc64le
- name_template: ghcr.io/jpkrohling/otelcol-distributions/tracing:{{ .Version }}
  image_templates:
  - ghcr.io/jpkrohling/otelcol-distributions/tracing:{{ .Version }}-386
  - ghcr.io/jpkrohling/otelcol-distributions/tracing:{{ .Version }}-amd64
  - ghcr.io/jpkrohling/otelcol-distributions/tracing:{{ .Version }}-arm64
  - ghcr.io/jpkrohling/otelcol-distributions/tracing:{{ .Version }}-ppc64le
