project_name: otelcol-loadbalancer
builds:
    - id: otelcol-loadbalancer
      goos:
        - darwin
        - linux
        - windows
      goarch:
        - "386"
        - amd64
        - arm64
        - ppc64le
      ignore:
        - goos: darwin
          goarch: "386"
        - goos: windows
          goarch: arm64
      dir: _build
      binary: otelcol-loadbalancer
      ldflags:
        - -s
        - -w
      flags:
        - -trimpath
      env:
        - CGO_ENABLED=0
archives:
    - id: otelcol-loadbalancer
      builds:
        - otelcol-loadbalancer
      name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
    - package_name: otelcol-loadbalancer
      contents:
        - src: otelcol-loadbalancer.service
          dst: /lib/systemd/system/otelcol-loadbalancer.service
        - src: otelcol-loadbalancer.conf
          dst: /etc/otelcol-loadbalancer/otelcol-loadbalancer.conf
          type: config|noreplace
        - src: otelcol.yaml
          dst: /etc/otelcol-loadbalancer/config.yaml
          type: config
      scripts:
        preinstall: preinstall.sh
        postinstall: postinstall.sh
        preremove: preremove.sh
      id: otelcol-loadbalancer
      builds:
        - otelcol-loadbalancer
      formats:
        - apk
        - deb
        - rpm
      maintainer: Juraci Paixão Kröhling <distributions@kroehling.de>
      description: otelcol-loadbalancer distribution of the OpenTelemetry Collector
      license: Apache 2.0
checksum:
    name_template: '{{ .ProjectName }}_checksums.txt'
dockers:
    - goos: linux
      goarch: "386"
      dockerfile: Dockerfile
      image_templates:
        - ghcr.io/jpkrohling/otelcol-distributions/otelcol-loadbalancer:{{ .Version }}-386
      extra_files:
        - otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/386
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: amd64
      dockerfile: Dockerfile
      image_templates:
        - ghcr.io/jpkrohling/otelcol-distributions/otelcol-loadbalancer:{{ .Version }}-amd64
      extra_files:
        - otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/amd64
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: arm64
      dockerfile: Dockerfile
      image_templates:
        - ghcr.io/jpkrohling/otelcol-distributions/otelcol-loadbalancer:{{ .Version }}-arm64
      extra_files:
        - otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/arm64
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: ppc64le
      dockerfile: Dockerfile
      image_templates:
        - ghcr.io/jpkrohling/otelcol-distributions/otelcol-loadbalancer:{{ .Version }}-ppc64le
      extra_files:
        - otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/ppc64le
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
docker_manifests:
    - name_template: ghcr.io/jpkrohling/otelcol-distributions/otelcol-loadbalancer:{{ .Version }}
      image_templates:
        - ghcr.io/jpkrohling/otelcol-distributions/otelcol-loadbalancer:{{ .Version }}-386
        - ghcr.io/jpkrohling/otelcol-distributions/otelcol-loadbalancer:{{ .Version }}-amd64
        - ghcr.io/jpkrohling/otelcol-distributions/otelcol-loadbalancer:{{ .Version }}-arm64
        - ghcr.io/jpkrohling/otelcol-distributions/otelcol-loadbalancer:{{ .Version }}-ppc64le
sboms:
    - id: archive
      artifacts: archive
    - id: package
      artifacts: package
