extensions:
  health_check: {}
  pprof: {}

receivers:
  otlp:
    protocols:
      grpc: {}
  jaeger:
    protocols:
      thrift_binary: {}
      thrift_compact: {}
      grpc: {}
  zipkin: {}

exporters:
  nop:
  otlp:
    endpoint: otlp.example.com:4317
  otlphttp:
    endpoint: https://otlp.example.com/otlp

service:
  extensions: [ health_check, pprof ]
  pipelines:
    traces:
      receivers:  [ otlp, jaeger, zipkin ]
      processors: [  ]
      exporters:  [ nop, otlp, otlphttp ]
