name: Continuous Integration - otelcol-tracing

on:
  workflow_run:
    workflows: [Continuous Integration]
    types:
      - completed

jobs:
  release:
    name: Continuous Integration - otelcol-tracing - GoReleaser
    uses: ./.github/workflows/base-goreleaser-ci.yaml
    with:
      distribution: otelcol-tracing
    secrets: inherit
