name: Continuous Integration - otelcol-otlp

on:
  workflow_run:
    workflows: [Continuous Integration]
    types:
      - completed

jobs:
  release:
    name: Continuous Integration - otelcol-otlp - GoReleaser
    uses: ./.github/workflows/base-goreleaser-ci.yaml
    with:
      distribution: otelcol-otlp
    secrets: inherit
