name: Continuous Integration - otelcol-loadbalancer

on:
  workflow_run:
    workflows: [Continuous Integration]
    types:
      - completed

jobs:
  release:
    name: Continuous Integration - otelcol-loadbalancer - GoReleaser
    uses: ./.github/workflows/base-goreleaser-ci.yaml
    with:
      distribution: otelcol-loadbalancer
    secrets: inherit
