name: Release tracing

on:
  workflow_run:
    workflows: [Continuous Integration - tracing]
    types:
      - completed

jobs:
  release:
    name: Release tracing
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: tracing
    secrets: inherit
