name: Release sidecar

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release:
    name: Release sidecar
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: sidecar
    secrets: inherit
