name: Release otelcol-tracing

on:
  release:
    types: [published]

jobs:
  release:
    name: Release otelcol-tracing
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol-tracing
      goos: '[ "linux", "windows", "darwin" ]'
      goarch: '[ "386", "amd64", "arm64", "ppc64le", "arm", "s390x" ]'
    secrets: inherit
    permissions: write-all
