name: Release tracing

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release:
    name: Release tracing
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: tracing
    secrets: inherit
