name: Release otelcol-otlp

on:
  release:
    types: [published]

jobs:
  release:
    name: Release otelcol-otlp
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol-otlp
    secrets: inherit
    permissions: write-all
